version: "3"
services:
    db:
        container_name: mysql8
        hostname: mysql
        image: mysql:8.0
        ports:
          - 3306:3306
        environment:
          #MYSQL_DATABASE: app
          #MYSQL_USER: app
          #MYSQL_PASSWORD: app
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - persistent:/var/lib/mysql
        restart: always
        networks:
         - localhost
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        hostname: phpmyadmin
        links:
          - db:db
        ports:
          - 8000:80
        environment:
          #MYSQL_USER: app
          #MYSQL_PASSWORD: app
          MYSQL_ROOT_PASSWORD: root
        restart: always
volumes:
    persistent:

networks:
  localhost:
    external: true
