version: '3'
services:
  app:
    container_name: wordpress
    image: webdevops/php-apache:8.2-alpine
    ports:
      - 80:80
    volumes:
      - ./public_html:/app/public_html
    environment:
      WEB_DOCUMENT_ROOT: /app/public_html
    network_mode: localhost
